monolog:
    handlers:
        main:
            type:  fingers_crossed
            handler: nested
            path:  '%kernel.logs_dir%/debug.log'
            level: debug
            # max number of log files to keep
            # defaults to zero, which means infinite files
            max_files: 1
        nested:
          type: stream
          path: "%kernel.logs_dir%/debug.log"
          level: debug
          channels: ["!event"]
        console:
          type: console
          process_psr_3_messages: false
          channels: ["!event", "!doctrine"]